# .streamlit/secrets.toml
valid_keys = ["TRIAL-2026", "PRO-KEY-X99", "RAKSHAN-ADMIN"]
GOOGLE_API_KEY = "AIzaSyA7cEptvpxOL7-PVNnWrk3uOtnAb10MjQE"
KEYGEN_ACCOUNT_ID = "51bb33ef-d469-4c06-ac4b-68b65ce1c647"
